# collect all parameters here for easy configuration

LINE_PID_P = 0.1
LINE_PID_D = 0.01
LINE_PID_I = 0.0

TURN_PID_P = 2.0
TURN_PID_D = 0.2
TURN_PID_I = 0.0

FORWARD_SPEED = 69.0
BACKWARD_SPEED = -30.0

BLACK_THRESHOLD_MAX = 150

TURN_OK_ERROR_THRESHOLD = 8

CAN_PUSH_TIME = 0.9
GO_BACK_TRESHOLD_TIME = 0.6

START_DIRECTION = 'l'