# collect all parameters here for easy configuration

LINE_PID_P = 0.1
LINE_PID_D = 0.01
LINE_PID_I = 0.0

TURN_PID_P = 1.5
TURN_PID_D = TURN_PID_P / 10.0
TURN_PID_I = 0.1

FORWARD_SPEED = 69.0
BACKWARD_SPEED = -30.0

BLACK_THRESHOLD_MAX = 180

TURN_OK_ERROR_THRESHOLD = 8
EXTRA_CYCLE_AFTER_TURN = 6

CAN_PUSH_TIME = 0.9
GO_BACK_TRESHOLD_TIME = 0.5

START_DIRECTION = 'l'